gclib: H_DownloadArraysFromList
H_DownloadArraysFromList()
GReturn H_DownloadArraysFromList (GCon g, ArrayNode * head, int fail)
Walks through the array linked list, downloading each.
Warning
This function will call DA and DM which modifies the controllers' array table. This should NOT be done while running record array (see RA/RC/RD) or while using the MODBUS array sharing feature (see ME). To prevent any possibility of array table issues, dimension all the arrays used in the applications with the appropriate lengths before use and comment out the array table modification section below.
Definition at line 136 of file arrays.c.
References G_BAD_RESPONSE_QUESTION_MARK, G_BOUNDS, G_NO_ERROR, GArrayDownload(), and GCmd().
Referenced by H_ArrayDownloadFromMemory().