gclib: examples.Examples.PrintError
PrintError()
static void PrintError (gclib gclib, Exception ex) inline static
Prints the exception to the console and queries the controller for the most recent error message.
Parameters
gclib The gclib object from where the exception originated.
ex The exception object caught by the example.
See commands_example.cs for an example.
Definition at line 39 of file examples.cs.
Referenced by Commands_Example.Main(), Contour_Example.Main(), IP_Assigner_Example.Main(), Jog_Example.Main(), Message_Example.Main(), Motion_Complete_Example.Main(), Position_Tracking_Example.Main(), Record_Position_Example.Main(), and Vector_Mode_Example.Main().