gclib: e
e()
void e (GReturn rc) inline
A trivial, C++ style return code check used in Galil's examples and demos.
Throws GReturn if return value is not G_NO_ERROR. See Commands_Example.cpp for example usage and catch() handler.
Definition at line 33 of file examples.h.
References G_NO_ERROR.
Referenced by check_interrupts(), commands(), contour(), H_ArrayDownloadFromMemory(), ip_assigner(), jog(), load_buf(), load_buffer(), message(), motion_complete(), position_tracking(), record_position(), remote_server(), vector(), and write_array_to_file().