gclib: load_buffer
load_buffer()
bool load_buffer (GCon g, ifstream & fs, int capacity)
Loads vector buffer with commands from the given text file.
Returns false when there are no more lines in the text file
Definition at line 88 of file vector.cpp.
References e(), and GCmd().
Referenced by vector().