gclib: GCmd
GCmd()
GReturn GCALL GCmd (GCon g, GCStringIn command)
Wrapper around GCommand for use when the return value is not desired.
The returned data is still checked for error, e.g. ? or timeout, but is not brought out through the prototype.
Parameters
g Connection's handle.
command Null-terminated command string to send to the controller.
Returns
The success status or error code of the function. See gclib_errors.h for possible values.
See x_gcommand.cpp for an example.
Definition at line 237 of file gclibo.c.
References G_SMALL_BUFFER, and GCommand().
Referenced by check_interrupts(), commands(), contour(), GRecordRate(), H_DownloadArraysFromList(), H_DownloadData(), jog(), load_buf(), load_buffer(), message(), motion_complete(), position_tracking(), record_position(), and vector().