gclib: motion_complete
motion_complete()
GReturn motion_complete (GCon g)
Uses interrupts to track when the motion of controller is completed.
Parameters
g Connection's handle.
Returns
The success status or error code of the function. See gclib_errors.h for possible values.
See motion_complete_example.cpp for an example.
Definition at line 18 of file motion_complete.cpp.
References check_interrupts(), e(), G_NO_ERROR, G_SMALL_BUFFER, G_UNSUPPORTED_FUNCTION, GCmd(), GCmdT(), GCommand(), GInterrupt(), and GTimeout().