gclib: vector
vector()
GReturn vector (GCon g, char * file)
Puts controller into Vector Mode and accepts a file defining vector points.
Parameters
g Connection's handle.
file A Path to a file that defines vector commands.
Returns
The success status or error code of the function. See gclib_errors.h for possible values.
See vector_example.cpp for an example.
Example text file:
VP -2219,-2667
VP -2523,-2832
VP 2844,-1425
VP 728,1971
VP 2127,183
VP -997,688
VP 725,-1893
VP 527,2899
VP -37,2523
VP 1277,1425
VP 857,2388
VP 1096,-1694
CR 1000,0,90
Definition at line 36 of file vector.cpp.
References e(), G_BAD_FILE, G_CONNECTION_NOT_ESTABLISHED, GCmd(), GCmdI(), GMotionComplete(), GSleep(), and load_buffer().